version: '3.8'
name: suggestion-box
services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${PORT_API}:7011"
    command: ["npm", "run", "start"]
    environment:
      - VERSION=${VERSION}
      - PORT=${PORT_API}
      # interact with mongo container in the same network
      - MONGODB_URI=mongodb://mongo:27017/suggestion-box
    restart: on-failure
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${PORT}:7010"
    environment:
      - VERSION=${VERSION}
      - PORT=${PORT}
      - NUXT_PUBLIC_API_BASE=http://localhost:${PORT_API}
    depends_on:
      - backend

  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    # Warning: we are exposing the port to the host machine
    ports:
      - "27017:27017"
