version: '3.8'
name: suggestion-box
services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    command: ["npm", "run", "start"]
    environment:
      - VERSION=${VERSION}
      - PORT=${PORT}
      # interact with mongo container in the same network
      - MONGODB_URI=mongodb://mongo:27017/suggestion-box
    depends_on:
      - mongo

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "7002:7002"
  #   depends_on:
  #     - backend

  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    # expose the port to the host machine if needed
    # ports:
      # - "27017:27017"
